### PR TITLE
Update kickass XML namespace

### PR DESCRIPTION
**Pull request by DirtyJerz**

### CODE REVIEW

**Comment by VeNoMouS** [comment]
Confirmed namespace has changed, thanks :)

**Comment by DirtyJerz** [comment]
Shouldn't we just scrape the namespace from the top of the file? That would patch future changes.

**Comment by VeNoMouS** [comment]
Yea, does sound better.. Heres a rough draft that I wrote before... should work in production... have tested it on the fly...

```
import requests
from StringIO import StringIO
import xml.etree.cElementTree as etree

req = requests.get('https://kat.cr/usearch/elementary?rss=1',verify=False,timeout=30)
 for event, elem in etree.iterparse(StringIO(req.content),("start-ns",)):
  if event == "start-ns":
   print elem[1]
```

or as a line liner..

```
 print tuple(elem[1] for (event, elem) in etree.iterparse(StringIO(req.content),("start-ns",)) if event == 'start-ns')[0]
```

Technically you don't even need that if since your only searching for start-ns and were pulling out the first element hit anyway... 

returns "//kastatic.com/xmlns/0.1/"

So i'll put this into production and test it more thoroughly

**Comment by VeNoMouS** [comment]
@DirtyJerz try out eda0b48631cd9e8f17fdf5132af8d3cd8016f217

**Comment by DirtyJerz** [comment]
sorry I never got back to you on this but it does work as expected. Thanks!

**Comment by VeNoMouS** [comment]
@DirtyJerz thanks for the update :)

**Pull request merged**
